const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANG_LANGUAGE: 'CHANGE_LANGUAGE',
    //admin
    FETCH_ROLE_START: 'FETCH_ROLE_START',
    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',

    FETCH_ALL_USER_SUCCESS: 'FETCH_ALL_USER_SUCCESS',
    FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',

    FETCH_OWNERS_SUCCESS: 'FETCH_OWNERS_SUCCESS',
    FETCH_OWNERS_FAILED: 'FETCH_OWNERS_SUCCESS',

    FETCH_TYPEHOUSE_SUCCESS: 'FETCH_TYPEHOUSE_SUCCESS',
    FETCH_TYPEHOUSE_FAILED: 'FETCH_TYPEHOUSE_FAILED',
    FETCH_TYPEHOUSE_START: 'FETCH_TYPEHOUSE_START',

    FETCH_CITY_SUCCESS: 'FETCH_CITY_SUCCESS',
    FETCH_CITY_FAILED: 'FETCH_CITY_FAILED',
    FETCH_CITY_START: 'FETCH_CITY_START',


    CREATE_POST_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_POST_FAILED: 'CREATE_USER_FAILED',

    FETCH_ALL_POST_SUCCESS: 'FETCH_ALL_POST_SUCCESS',
    FETCH_ALL_POST_FAILED: 'FETCH_ALL_POST_FAILED'



})

export default actionTypes;